name: "Github Release"
description: "Triggers a GitHub release of a version"
inputs:
  version:
    description: The version to release
    required: true
  body:
    description: Release summary
    required: false
    default: ""
  application-name:
    description: The name of the application that should be released. The name should not contain spaces
    required: false
    default: ""
  token:
    description: Token to use for Github API
    required: false
    default: ${{ github.token }}
outputs:
  upload_url:
    description: The URL for uploading assets to the release

runs:
  using: "node16"
  main: "release/index.js"
