name: 'Github Release'
description: 'Triggers a GitHub release of a version'
inputs:
  token:
    description: Token to use for Github API
    required: true
    default: ${{ github.token }}
  version:
    description: The version to release
    required: true
  body:
    description: Release summary
    required: false
    default: ''
  
runs:
  using: 'node12'
  main: 'release/index.js'