name: Github JavaScript Actions CI

on: [push, pull_request]

jobs:
  build:
    name: Build and Test 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn
    - run: yarn release
    - name: Establish context
      id: context
      uses: dolittle/establish-context-action@v2

    - name: Increment version
      id: increment-version
      if: ${{ steps.context.outputs.should-publish == 'true' }}
      uses: dolittle/increment-version-action@v2
      with:
        version: ${{ steps.context.outputs.current-version }}
        release-type: ${{ steps.context.outputs.release-type }}

    - name: Create GitHub Release
      if: ${{ steps.context.outputs.should-publish == 'true' }}
      uses: ./
      with:
        cascading-release: ${{ steps.context.outputs.cascading-release }}
        version: ${{ increment-version.next-version }}

  release:
    name: Release JavaScript GitHub Action
    needs: build
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn
    - name: Release GitHub Action
      uses: technote-space/release-github-actions@v6
      with:
        BUILD_COMMAND: yarn release
        CLEAN_TARGETS: Source,*.ts,*.js,*.json,*.lock,.[!.]*,Tests,Documentation,node_modules,Distribution
        TEST_TAG_PREFIX: test/
        ORIGINAL_TAG_PREFIX: original/
        CLEAN_TEST_TAG: true

