name: Github JavaScript Actions CI

on:
  push:
    branches:
    - '**'
  pull_request:
    types: [closed]

jobs:
  build:
    name: Build and Test 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn
    - run: yarn release
    - name: Establish context
      id: context
      uses: dolittle/establish-context-action@v2

    - name: Increment version
      id: increment-version
      if: ${{ steps.context.outputs.should-publish == 'true' }}
      uses: dolittle/increment-version-action@v2
      with:
        version: ${{ steps.context.outputs.current-version }}
        release-type: ${{ steps.context.outputs.release-type }}

    - name: Create GitHub Release
      if: ${{ steps.context.outputs.should-publish == 'true' }}
      uses: ./
      with:
        token: ${{ secrets.BUILD_PAT }}
        cascading-release: ${{ steps.context.outputs.cascading-release }}
        version: ${{ steps.increment-version.outputs.next-version }}

    - name: Release GitHub Action
      if: startsWith(github.ref, 'refs/tags/')
      uses: technote-space/release-github-actions@v6
      with:
        BUILD_COMMAND: yarn release
        CLEAN_TARGETS: Source,*.ts,*.js,*.json,*.lock,.[!.]*,Tests,Documentation,node_modules,Distribution
        TEST_TAG_PREFIX: test/
        ORIGINAL_TAG_PREFIX: original/
        CLEAN_TEST_TAG: true

